import ts from 'typescript';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import { DatabaseSync } from 'node:sqlite';
const require = createRequire(import.meta.url);
const moduleUrl = code => 'data:text/javascript;base64,' + Buffer.from(ts.transpileModule(code, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText).toString('base64');
const domainUrl = moduleUrl(await fs.readFile('lib/studentstay.ts', 'utf8'));
const domain = await import(domainUrl);
const sqlite = new DatabaseSync(':memory:');
sqlite.exec(await fs.readFile('drizzle/0000_lumpy_toad.sql', 'utf8'));
const adapter = { prepare(sql) { const stmt = sqlite.prepare(sql); return { bind(...args) { return { first: async () => stmt.get(...args) ?? null, all: async () => ({ results: stmt.all(...args) }), run: async () => { const r = stmt.run(...args); return { meta: { changes: Number(r.changes) } }; } }; } }; } };
globalThis.__stayTest = { env: { DB: adapter }, user: null };
let code = await fs.readFile('lib/server.ts', 'utf8');
code = code.replace('import { env } from "cloudflare:workers";', 'const env = globalThis.__stayTest.env;').replace('import { getChatGPTUser } from "@/app/chatgpt-auth";', 'const getChatGPTUser = async () => globalThis.__stayTest.user;').replace('from "zod"', 'from ' + JSON.stringify(pathToFileURL(require.resolve('zod')).href)).replace('from "./studentstay"', 'from ' + JSON.stringify(domainUrl));
const guards = await import(moduleUrl(code));
const snapshot = JSON.parse(await fs.readFile('lib/current-sheet.json', 'utf8'));
const data = domain.normalize(snapshot.sheets, snapshot.asOf, true);
const action = data.actions.find(a => a.status === 'NOT_SENT');
assert.equal((await guards.assertApproval(data, action.id, action.hash)).id, action.id);
const blocked = async (edit, hash = action.hash) => { const d = structuredClone(data); edit(d); await assert.rejects(() => guards.assertApproval(d, action.id, hash), guards.ApiError); };
await blocked(d => { d.preferences.ready = false; });
await blocked(d => { d.preferences.selectedOfferId = 'OF-0000000000000000'; });
await blocked(d => { d.actions.find(a => a.id === action.id).body += ' changed'; });
await blocked(d => { d.actions.find(a => a.id === action.id).recipient = 'someone@example.com'; });
await blocked(d => { d.actions.find(a => a.id === action.id).status = 'CLAIMED'; });
await blocked(d => { d.offers.find(o => o.id === action.offerId).status = 'HUMAN_ONLY'; });
await blocked(d => { d.offers.find(o => o.id === action.offerId).decision = 'SELECTED'; });
await blocked(() => {}, '0'.repeat(64));
assert.throws(() => guards.changeSchema.parse({ selectedOfferId: action.offerId }));
assert.throws(() => guards.changeSchema.parse({ latestMoveIn: '2027-02-31' }));
assert.throws(() => guards.validatePreferences({ ...data.preferences, minLease: 52, maxLease: 26 }));
await assert.rejects(() => guards.userFor(new Request('https://studentstay.example/api/state')), e => e.status === 401);
globalThis.__stayTest.user = { userId: 'test-owner' };
await assert.rejects(() => guards.userFor(new Request('https://studentstay.example/api/preferences', { headers: { origin: 'https://other.example' } }), true), e => e.status === 403);
await guards.userFor(new Request('https://studentstay.example/api/preferences', { headers: { origin: 'https://studentstay.example' } }), true);
let writes = 0; const request = crypto.randomUUID();
await guards.exclusive(request, 'test-owner', 'selection', {}, async () => ++writes);
await assert.rejects(() => guards.exclusive(request, 'test-owner', 'selection', {}, async () => ++writes), e => e.status === 409);
assert.equal(writes, 1);
await assert.rejects(() => guards.exclusive(crypto.randomUUID(), 'test-owner', 'approval', {}, async () => { throw new guards.ApiError('Unknown external result', 503); }));
await assert.rejects(() => guards.exclusive(crypto.randomUUID(), 'test-owner', 'approval', {}, async () => ++writes), e => e.status === 409);
assert.equal(writes, 1);
console.log('PASS — approval payload, selection, recipient, human-only, consumed-action, authentication, origin, preference validation, request replay and uncertain-response lock safeguards. No external requests or drafts.');
sqlite.close();
